# Generated by Django 5.2.3 on 2025-11-23 12:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crane_name', models.CharField(max_length=100, unique=True)),
                ('crane_type', models.CharField(default='EOT', max_length=50)),
                ('capacity_tonnes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('working', 'Working'), ('idle', 'Idle'), ('maintenance', 'Maintenance'), ('error', 'Error')], default='idle', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('device_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IoTGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_name', models.CharField(max_length=100, unique=True)),
                ('gateway_type', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='active', max_length=20)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CraneConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_rate', models.DecimalField(decimal_places=4, default=0.15, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('target_energy_per_ton', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('max_load_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('warning_threshold', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('overload_threshold', models.DecimalField(decimal_places=2, default=95.0, max_digits=5)),
                ('target_availability', models.DecimalField(decimal_places=2, default=90.0, max_digits=5)),
                ('target_performance', models.DecimalField(decimal_places=2, default=95.0, max_digits=5)),
                ('target_quality', models.DecimalField(decimal_places=2, default=99.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crane', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cranes.crane')),
            ],
        ),
        migrations.CreateModel(
            name='CraneAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_one', models.BooleanField(default=False)),
                ('alarm_two', models.BooleanField(default=False)),
                ('alarm_three', models.BooleanField(default=False)),
                ('alarm_message', models.TextField(blank=True)),
                ('alarm_severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('alarm_type', models.CharField(blank=True, max_length=50)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('crane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cranes.crane')),
            ],
            options={
                'indexes': [models.Index(fields=['crane', 'timestamp'], name='cranes_cran_crane_i_b16b5f_idx'), models.Index(fields=['timestamp'], name='cranes_cran_timesta_c2358a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CraneIOStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.BooleanField(default=False)),
                ('stop', models.BooleanField(default=False)),
                ('hoist_up', models.BooleanField(default=False)),
                ('hoist_down', models.BooleanField(default=False)),
                ('ct_left', models.BooleanField(default=False)),
                ('ct_right', models.BooleanField(default=False)),
                ('lt_forward', models.BooleanField(default=False)),
                ('lt_reverse', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('crane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cranes.crane')),
            ],
            options={
                'indexes': [models.Index(fields=['crane', 'timestamp'], name='cranes_cran_crane_i_f5db37_idx'), models.Index(fields=['timestamp'], name='cranes_cran_timesta_cc2164_idx')],
            },
        ),
        migrations.CreateModel(
            name='CraneLoadcellMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('load_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('overload', 'Overload')], default='normal', max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('crane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cranes.crane')),
            ],
            options={
                'indexes': [models.Index(fields=['crane', 'timestamp'], name='cranes_cran_crane_i_f70fbf_idx'), models.Index(fields=['timestamp'], name='cranes_cran_timesta_748143_idx')],
            },
        ),
        migrations.CreateModel(
            name='CraneMotorMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoist_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('hoist_current', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('hoist_power', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('hoist_frequency', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ct_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ct_current', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ct_power', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ct_frequency', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('lt_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('lt_current', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('lt_power', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('lt_frequency', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_power', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_current', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('crane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cranes.crane')),
            ],
            options={
                'indexes': [models.Index(fields=['crane', 'timestamp'], name='cranes_cran_crane_i_306362_idx'), models.Index(fields=['timestamp'], name='cranes_cran_timesta_cbe431_idx')],
            },
        ),
        migrations.CreateModel(
            name='CraneGatewayMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mqtt_topic', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('crane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cranes.crane')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cranes.iotgateway')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('crane',), name='unique_active_crane_mapping')],
            },
        ),
        migrations.CreateModel(
            name='MQTTMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('message_type', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('crane', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cranes.crane')),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cranes.iotgateway')),
            ],
            options={
                'indexes': [models.Index(fields=['crane', 'timestamp'], name='cranes_mqtt_crane_i_90a834_idx'), models.Index(fields=['topic'], name='cranes_mqtt_topic_19fba2_idx')],
            },
        ),
    ]
