# Generated by Django 5.2.8 on 2025-11-23 16:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cranes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CraneDailyKPIs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(max_length=20)),
                ('total_operation_time', models.DurationField(blank=True, null=True)),
                ('total_lifts', models.IntegerField(default=0)),
                ('total_mass_moved_tonnes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_energy_kwh', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_energy_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_energy_per_ton', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('average_efficiency', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('peak_load', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_power_demand', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('availability', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('performance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quality', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('oee', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cranes.crane')),
            ],
            options={
                'indexes': [models.Index(fields=['crane', 'date'], name='cranes_cran_crane_i_832349_idx')],
                'constraints': [models.UniqueConstraint(fields=('crane', 'date', 'shift'), name='unique_crane_daily_kpis')],
            },
        ),
        migrations.CreateModel(
            name='CraneHourlyKPIs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_start', models.DateTimeField()),
                ('hour_end', models.DateTimeField()),
                ('hoist_up_time', models.DurationField(blank=True, null=True)),
                ('hoist_down_time', models.DurationField(blank=True, null=True)),
                ('ct_left_time', models.DurationField(blank=True, null=True)),
                ('ct_right_time', models.DurationField(blank=True, null=True)),
                ('lt_forward_time', models.DurationField(blank=True, null=True)),
                ('lt_reverse_time', models.DurationField(blank=True, null=True)),
                ('stop_time', models.DurationField(blank=True, null=True)),
                ('total_motion_time', models.DurationField(blank=True, null=True)),
                ('hoist_up_count', models.IntegerField(default=0)),
                ('hoist_down_count', models.IntegerField(default=0)),
                ('ct_left_count', models.IntegerField(default=0)),
                ('ct_right_count', models.IntegerField(default=0)),
                ('lt_forward_count', models.IntegerField(default=0)),
                ('lt_reverse_count', models.IntegerField(default=0)),
                ('stop_count', models.IntegerField(default=0)),
                ('total_lifts', models.IntegerField(default=0)),
                ('total_mass_moved_tonnes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_load_per_lift', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_energy_kwh', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('hourly_energy_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('energy_per_ton', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('system_efficiency', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('availability', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('performance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quality', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('oee', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_power', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('peak_power', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('crane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cranes.crane')),
            ],
            options={
                'indexes': [models.Index(fields=['crane', 'hour_start'], name='cranes_cran_crane_i_9a4fa1_idx')],
                'constraints': [models.UniqueConstraint(fields=('crane', 'hour_start'), name='unique_crane_hourly_kpis')],
            },
        ),
    ]
