# Generated by Django 5.2.3 on 2025-11-24 06:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cranes', '0002_cranedailykpis_cranehourlykpis'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPointMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoming_field_name', models.CharField(max_length=100)),
                ('mapped_field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('motor_voltage', 'Motor Voltage'), ('motor_current', 'Motor Current'), ('motor_power', 'Motor Power'), ('motor_frequency', 'Motor Frequency'), ('load', 'Load'), ('capacity', 'Capacity'), ('io_status', 'IO Status'), ('alarm', 'Alarm')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('crane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cranes.crane')),
            ],
            options={
                'unique_together': {('crane', 'incoming_field_name')},
            },
        ),
    ]
