# Generated by Django 5.2.3 on 2025-11-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cranes', '0003_datapointmapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datapointmapping',
            options={'verbose_name': 'Data Point Mapping', 'verbose_name_plural': 'Data Point Mappings'},
        ),
        migrations.AddField(
            model_name='datapointmapping',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of this data point'),
        ),
        migrations.AddField(
            model_name='datapointmapping',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='datapointmapping',
            name='incoming_field_name',
            field=models.CharField(help_text='Field name from MQTT payload', max_length=100),
        ),
        migrations.AlterField(
            model_name='datapointmapping',
            name='mapped_field_name',
            field=models.CharField(help_text='Field name in our system', max_length=100),
        ),
    ]
